	
//console.log(

MDN_Events_List = "DOMContentLoaded\
	DOMMenuItemActive\
	DOMMenuItemInactive\
	MozAudioAvailable\
	MozGamepadButtonDown\
	MozGamepadButtonUp\
	MozOrientation\
	MozScrolledAreaChanged\
	Non-standard events\
	RadioStateChange\
	SVGAbort\
	SVGError\
	SVGLoad\
	SVGResize\
	SVGScroll\
	SVGUnload\
	SVGZoom\
	SpeechSynthesis\
	SpeechSynthesisError\
	Telephony\
	ValueChange\
	Web_Audio\
	abort\
	afterprint\
	afterscriptexecute\
	alerting\
	animationend\
	animationiteration\
	animationstart\
	audioprocess\
	beforeinstallprompt\
	beforeprint\
	beforescriptexecute\
	beforeunload\
	beginEvent\
	blur\
	broadcast\
	busy\
	cached\
	callschanged\
	canplay\
	canplaythrough\
	cardstatechange\
	cfstatechange\
	change\
	chargingchange\
	chargingtimechange\
	checking\
	click\
	command\
	commandupdate\
	compassneedscalibration\
	complete\
	compositionend\
	compositionstart\
	compositionupdate\
	connected\
	connecting\
	connectionInfoUpdate\
	contextmenu\
	copy\
	cut\
	datachange\
	dataerror\
	dblclick\
	delivered\
	devicechange\
	devicelight\
	devicemotion\
	deviceorientation\
	deviceproximity\
	dialing\
	disabled\
	dischargingtimechange\
	disconnected\
	disconnecting\
	downloading\
	drag\
	dragend\
	dragenter\
	dragleave\
	dragover\
	dragstart\
	drop\
	durationchange\
	emptied\
	enabled\
	endEvent\
	ended\
	error\
	experimental_inline\
	focus\
	focusin\
	focusout\
	fullscreenchange\
	fullscreenerror\
	gamepadconnected\
	gamepaddisconnected\
	gotpointercapture\
	hashchange\
	held\
	holding\
	icccardlockerror\
	iccinfochange\
	incoming\
	input\
	invalid\
	keydown\
	keypress\
	keyup\
	levelchange\
	load\
	loadeddata\
	loadedmetadata\
	loadend\
	loadstart\
	localized\
	lostpointercapture\
	mousedown\
	mouseenter\
	mouseleave\
	mousemove\
	mouseout\
	mouseover\
	mouseup\
	mozbrowseractivitydone\
	mozbrowserasyncscroll\
	mozbrowseraudioplaybackchange\
	mozbrowsercaretstatechanged\
	mozbrowserclose\
	mozbrowsercontextmenu\
	mozbrowserdocumentfirstpaint\
	mozbrowsererror\
	mozbrowserfindchange\
	mozbrowserfirstpaint\
	mozbrowsericonchange\
	mozbrowserloadend\
	mozbrowserloadstart\
	mozbrowserlocationchange\
	mozbrowsermanifestchange\
	mozbrowsermetachange\
	mozbrowseropensearch\
	mozbrowseropentab\
	mozbrowseropenwindow\
	mozbrowserresize\
	mozbrowserscroll\
	mozbrowserscrollareachanged\
	mozbrowserscrollviewchange\
	mozbrowsersecuritychange\
	mozbrowserselectionstatechanged\
	mozbrowsershowmodalprompt\
	mozbrowsertitlechange\
	mozbrowserusernameandpasswordrequired\
	mozbrowservisibilitychange\
	moztimechange\
	notificationclick\
	notimplemented_inline\
	noupdate\
	obsolete\
	offline\
	online\
	orientationchange\
	overflow\
	pagehide\
	pageshow\
	paste\
	pause\
	play\
	playing\
	pointercancel\
	pointerdown\
	pointerenter\
	pointerleave\
	pointerlockchange\
	pointerlockerror\
	pointermove\
	pointerout\
	pointerover\
	pointerup\
	popstate\
	popuphidden\
	popuphiding\
	popupshowing\
	popupshown\
	progress\
	push\
	pushsubscriptionchange\
	ratechange\
	readystatechange\
	received\
	repeatEvent\
	reset\
	resize\
	resourcetimingbufferfull\
	resuming\
	scroll\
	seeked\
	seeking\
	select\
	sent\
	show\
	smartcard-insert\
	smartcard-remove\
	stalled\
	statechange\
	statuschange\
	stkcommand\
	stksessionend\
	storage\
	submit\
	suspend\
	timeout\
	timeupdate\
	touchcancel\
	touchend\
	touchenter\
	touchleave\
	touchmove\
	touchstart\
	transitionend\
	underflow\
	unload\
	updateready\
	userproximity\
	ussdreceived\
	visibilitychange\
	voicechange\
	voiceschanged\
	volumechange\
	waiting\
	wheel".split( /\s+/mg );

//);
